### ISSUE TITLE
Can not configure IP on SVI interface

### ISSUE THREAD

**Issue by Hemakuma** [datacenter/nxtoolkit#7]
i created SVI but i am not able to assign ip address to it. i am usin NX.IP() module but it is complaining..
    ipv4.add_interface_address(svi1, '192.168.50.1/24')
  File "build/bdist.linux-x86_64/egg/nxtoolkit/nxtoolkit.py", line 4541, in add_interface_address
TypeError: Interface or PortChannel instance expected

Or is there a different way to configure SVI ip.

thanks
Hemant

**Comment by fractlrao** [comment]
You can use the below steps to assign ip addressn to SVI:
    svi1 = NX.SVI('vlan33')

```
ipv4 = NX.IP()
ipv4.add_interface_address(svi1, '1.1.1.1/20')

session.push_to_switch(svi1.get_url(), svi1.get_json())
session.push_to_switch(ipv4.get_url(), ipv4.get_json())
```
